### ISSUE TITLE
Custom Actor ID

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge-swift#103]
Actor ID is missing a public init. I would like to init the Actor with a given custom string

**Comment by heckj** [comment]
The core library (as far as I know, intentionally) doesn't allow you to specify your own custom actorID. That is managed by the Automerge core library, and provided to us (which is why it doesn't have a public initializer). There's no current way to create an Automerge document with your own specified actorID.

I believe @alexjg and the core team have been leaning towards wanting to even remove the concept of an ActorID if they can - but that's "down the road" in terms of efforts on the overall project.

**Comment by alexjg** [comment]
The core library does actually expose ways to construct your own actor ID, I just didn't expose those methods here. I do think exposing ways to set the actor ID is a big old footgun but that doesn't mean we shouldn't, just that we should try and find ways not to :slightly_smiling_face: .

@lightsprint09 what's your usecase?

**Comment by lightsprint09** [comment]
Just check my code... looks like I don't need them anymore :)
