### ISSUE TITLE
Distribute xcframework in separate repo

### ISSUE THREAD

**Issue by lightsprint09** [automerge/automerge-swift#20]
As done in automerge-swift, the binary can be packaged and deployed into a separate GitHub repo, which helps to reduce the size of this repository

**Comment by heckj** [comment]
Hey Lucas!

It does make for a heavier repo, but solves the two-repo dance step moves otherwise needed for updating a release while we're iterating on this. I'm reasonably confident we could build tagged releases and still include them as release artifacts in this repo and reference it from this repo as well based on some experiments I did elsewhere. 

In the meantime, @Alexjg set it up such that we're only building and including a full XCFramework.zip in the tagged points where we cut a release to keep with the local reference functionality.

**Comment by heckj** [comment]
Resolved as of the 0.1.1 release - there's [a release process detailing the setup](https://github.com/automerge/automerge-swifter/blob/main/notes/release-process.md), but the XCFramework is now hosted from GitHub releases, although not from a separate repository.
